# Greedy problems


## <span style="color:violet">예제 문제</span>

### <span style="color:lime">1. 거스름돈 문제</span>

총 n 원을 받았을 때 동전으로 어떻게 교환할 수 있을까?
사용할 동전 500원, 100원, 50원, 10원이 무한이 있다.

In [12]:
# total money is n
n = int(input())

# coin list
coins = [500, 100, 50, 10]

# result list
res = []

for coin in coins:
  res.append(n // coin)
  n %= coin

print('coin list: ', res)
print('the number of coins: ',sum(res))

coin list:  [2, 0, 0, 0]
the number of coins:  2


### <span style="color:lime">2. 큰 수의 법칙</span>

주어진 수(배열)를 이용해 가장 큰 수를 만드는 방법을 구하라
- 조건
2 <= n <= 1000, 1 <= m <= 10000, 1 <= k <= 10000<br>
n개의 수를 m번 더하여 가장 큰수를 만들며, k번을 초과하여 더해줄 수 없다.

In [18]:
m, k = map(int, input().split())

data = list(map(int, input().split()))

data.sort(reverse=True)

first = data[0]
second = data[1]

res = 0 
while True:
  for i in range(k):
    if m == 0:
      break
    res += first

  if m == 0:
    break

  res += second
  m -= 1

print(res)



42


### <span style="color:lime">3. 숫자 카드 게임</span>

주어진 카드 중에 가장 높은 숫자가 쓰인 카드를 뽑는 게임이다. <br>
1. 행을 선택한다
2. 해당하는 행의 카드 중 가장 낮은 숫자를 선택한다.

In [22]:
n, m = map(int, input().split())

res = 0

for row in range(n):
  data = list(map(int, input().split()))
  row_min = min(data)
  res = max(res, row_min)

print(res)

2


In [40]:
import numpy as np
rows, cols = map(int, input().split())

data = np.zeros(shape=(rows,cols), dtype=int)

# get data from user's input
for row in range(rows):
  temp = list(map(int, input().split()))
  data[row] = temp

# find solution
print(np.max(np.min(data,axis=1)))

2


Numpy array test is presented as follows:

In [33]:
test = np.array([[3,4,2],[2,4,3]])
test = np.random.randint(4, size=(3,3))
print(test)
print(test[1])
test[1] = [2,2,2]
print(test)

[[0 0 2]
 [1 2 0]
 [1 3 3]]
[1 2 0]
[[0 0 2]
 [2 2 2]
 [1 3 3]]


### <span style="color:lime">4. 1이 될 때까지</span>

어떠한 N이 1이 될 때까지 다음의 두 과정 중 하나를 반복적으로 선택하여 수행했을 때 최소 수행해야하는 횟수는?
- n에서 1 뺀다
- n을 k로 나눈다

In [6]:
n, k = map(int, input().split())

res = 0
while True:
  if n%k == 0:
    break
  n -= 1
  res += 1

while True:
  if n == 1:
    break
  n = n/k
  res += 1

print(res)


2


## <span style="color:violet">연습 문제</span>

### <span style="color:lime">모험가 길드</span>

공포도가 x인 모험가는 반드시 x명 이상으로 구성한 모험가 그룹에 참여해야함

In [16]:
# example inputs
# n = 5
# data = [2, 3, 1, 2, 2]

# This is the number of inputs and data
n = int(input())
data = list(map(int, input().split()))

# sort out data [descending order]
data.sort(reverse=True)

res=0

while True:
  res+=1
  groupSize = data[0]
  if groupSize >= len(data):
    break
  remainedGroupSize = groupSize-1
  data=data[1:-remainedGroupSize]

print(res)

2


### <span style="color:lime">곱하기 혹은 더하기</span>

In [29]:
# example inputs
# n = '02984'

# input
n = str(input())
print(n)

res=0
for i in range(len(n)):
  num = int(n[i])

  if i == 0:
    res += num
    continue

  # before_num = int(n[i-1])
  if res != 0 and num != 0:
    res *= num
  else:
    res += num

print(res)

02984
576
