# Greedy problems


## <span style="color:violet">예제 문제</span>

### <span style="color:lime">1. 거스름돈 문제</span>

총 n 원을 받았을 때 동전으로 어떻게 교환할 수 있을까?
사용할 동전 500원, 100원, 50원, 10원이 무한이 있다.

In [12]:
# total money is n
n = int(input())

# coin list
coins = [500, 100, 50, 10]

# result list
res = []

for coin in coins:
  res.append(n // coin)
  n %= coin

print('coin list: ', res)
print('the number of coins: ',sum(res))

coin list:  [2, 0, 0, 0]
the number of coins:  2


### <span style="color:lime">2. 큰 수의 법칙</span>

주어진 수(배열)를 이용해 가장 큰 수를 만드는 방법을 구하라
- 조건
2 <= n <= 1000, 1 <= m <= 10000, 1 <= k <= 10000<br>
n개의 수를 m번 더하여 가장 큰수를 만들며, k번을 초과하여 더해줄 수 없다.

In [18]:
m, k = map(int, input().split())

data = list(map(int, input().split()))

data.sort(reverse=True)

first = data[0]
second = data[1]

res = 0 
while True:
  for i in range(k):
    if m == 0:
      break
    res += first

  if m == 0:
    break

  res += second
  m -= 1

print(res)



42


### <span style="color:lime">3. 숫자 카드 게임</span>

주어진 카드 중에 가장 높은 숫자가 쓰인 카드를 뽑는 게임이다. <br>
1. 행을 선택한다
2. 해당하는 행의 카드 중 가장 낮은 숫자를 선택한다.

In [22]:
n, m = map(int, input().split())

res = 0

for row in range(n):
  data = list(map(int, input().split()))
  row_min = min(data)
  res = max(res, row_min)

print(res)

2


In [40]:
import numpy as np
rows, cols = map(int, input().split())

data = np.zeros(shape=(rows,cols), dtype=int)

# get data from user's input
for row in range(rows):
  temp = list(map(int, input().split()))
  data[row] = temp

# find solution
print(np.max(np.min(data,axis=1)))

2


Numpy array test is presented as follows:

In [33]:
test = np.array([[3,4,2],[2,4,3]])
test = np.random.randint(4, size=(3,3))
print(test)
print(test[1])
test[1] = [2,2,2]
print(test)

[[0 0 2]
 [1 2 0]
 [1 3 3]]
[1 2 0]
[[0 0 2]
 [2 2 2]
 [1 3 3]]


### <span style="color:lime">4. 1이 될 때까지</span>

어떠한 N이 1이 될 때까지 다음의 두 과정 중 하나를 반복적으로 선택하여 수행했을 때 최소 수행해야하는 횟수는?
- n에서 1 뺀다
- n을 k로 나눈다

In [6]:
n, k = map(int, input().split())

res = 0
while True:
  if n%k == 0:
    break
  n -= 1
  res += 1

while True:
  if n == 1:
    break
  n = n/k
  res += 1

print(res)


2


## <span style="color:violet">연습 문제</span>

### <span style="color:lime">모험가 길드</span>

공포도가 x인 모험가는 반드시 x명 이상으로 구성한 모험가 그룹에 참여해야함

In [16]:
# example inputs
# n = 5
# data = [2, 3, 1, 2, 2]

# This is the number of inputs and data
n = int(input())
data = list(map(int, input().split()))

# sort out data [descending order]
data.sort(reverse=True)

res=0

while True:
  res+=1
  groupSize = data[0]
  if groupSize >= len(data):
    break
  remainedGroupSize = groupSize-1
  data=data[1:-remainedGroupSize]

print(res)

2


### <span style="color:lime">곱하기 혹은 더하기</span>

In [31]:
# example inputs
# n = '02984'

# input
n = str(input())
print(n)

res=0
for i in range(len(n)):
  num = int(n[i])

  if i == 0:
    res += num
    continue

  # before_num = int(n[i-1])
  if res != 0 and num != 0:
    res *= num
  else:
    res += num



02847
448


### <span style="color:lime">문자열 뒤집기</span>

In [41]:
# example 0001100
# n = '0001100'

n = str(input())

count0 = 0
count1 = 0

if int(n[0])==0:
  count1 += 1
else:
  count0 += 1

for i in range(1, len(n)):
  if int(n[i]) != int(n[i-1]):
    if int(n[i])==0:
      count1 += 1
    else:
      count0 += 1
  
print(min(count0, count1))


1


### <span style="color:lime">만들 수 없는 금액</span>

N개의 동전을 이요하여 만들 수 없는 야의 정수 금액 중 최솟값 구하기

In [48]:
# example inputs
# n = 5
# data = [3,2,1,1,9]

# inputs
n = int(input())
data = list(map(int, input().split()))

data.sort(reverse=True)
# print(data)

num = 1
temp = 0
while True:
  temp = num
  for i in range(len(data)):
    if temp >= data[i]:
      temp = temp - data[i]
      if temp == 0:
        break
  
  if temp != 0:
    break

  num += 1

print(num)

[9, 3, 2, 1, 1]
8


### <span style="color:lime">볼링공 고르기</span>

서로 다른 무게 볼링공을 고르기. 같은 무게라 할지라도 다른 볼링공으로 간주한다.

In [51]:
# example inputs
n, m = map(int, input().split())
balls = list(map(int, input().split()))

count = 0
for i in range(len(balls)):
  for j in range(i+1, len(balls)):
    if balls[i] != balls[j]:
      count += 1

print(count)


25


### <span style="color:lime">무지의 먹방 라이브</span>

In [67]:
def solution(food_times, k):
  k = k+1 # add 1 because of the moment when he eat again after 5초
  answer =0

  while True:
    for i in range(len(food_times)):
      print(food_times)

      if food_times != 0:
        food_times[i] -= 1
        k -= 1
        answer = (i+1)%len(food_times)+1
      else:
        continue

      if k == 0:
        break
    
    if k == 0:
      break``
    
  return answer


food_times = [3,1,2]
k = 5

solution(food_times, k)

[3, 1, 2]
[2, 1, 2]
[2, 0, 2]
[2, 0, 1]
[1, 0, 1]
[1, -1, 1]


1